name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Contrôle des vulnérabilités (Trivy FS)
        run: |
          docker run --rm -v ${{ github.workspace }}:/app aquasec/trivy:latest fs /app \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --exit-code 1

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances # Ce job ne se lance que si 'Dependances' est vert
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Linting Dockerfile (Hadolint)
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile
